# _config.yml
title: Ergin Çağatay Çankaya  
email: ergin@ualberta.ca  
description: >  
  PhD Candidate @ University of Alberta | Forest growth models, remote sensing & LiDAR  
baseurl: ""        # no sub-path
url: "https://ergincagataycankaya.github.io"

# choose the built-in minima theme
theme: minima

# include folders so Jekyll will copy them straight through
include:
  - cv
  - assets

# where your markdown pages live
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Build settings
markdown: kramdown
